
public class Menu {
	
	private String name;
	private String password;
	private String error;
	
	
	
	/**
	 * @param name create account with this name
	 * @param password create account with this password
	 */
	public Menu(String name, String password) {
		super();
		this.name = name;
		this.password = password;
		this.error = "";
	}

	public void openAccount() {
		
	}
	
	/**
	 * @param name login name
	 * @param password login password
	 */
	public void logInExistAccount(String name, String password) {
		this.error = "Access Deny";
		if (this.name == name && this.password == password) {
			this.error = "Welcome!";
		}
	}
	
	/**
	 * @param requestHelp kind of help
	 * @return autogenerated response related to the request of help
	 */
	public String help(String requestHelp) {
		String help = "for more contact us";
		switch(requestHelp) {
		case "problem password":
			help = "automatic answer for password problems";
			break;
		case "user name":
			help = "automatic answer for user name problems";
			break;
		case "email verification":
			help = "automatic answer for email verification problems";
			break;
		case "code referral":
			help = "automatic answer for code referral problems";
			break;
		default :
			break;
		}
		
		return help;
	}
	
	/**
	 *  delete user and say goodbye
	 */
	public void Quit() {
		
		this.name = "";
		this.password = "";
		
		System.out.println("Goodbye");
		
	}

}
